AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example template for deploying a AWS Lambda with relevant chaos configuration.

Globals:
  Function:
    Timeout: 10

Resources:
  
  ChaosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DotnetChaosLambda.FunctionTest
      Handler: DotnetChaosLambda.FunctionTest::DotnetChaosLambda.FunctionTest.Function::LambdaHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          CHAOS_PARAM: "{	\"FaultType\": \"exception\",	\"Delay\": 400,	\"IsEnabled\": true,	\"ErrorCode\": 404,	\"ExceptionMsg\": \"chaos\",	\"Rate\": 1 }"
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /chaos
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chaos/"
