AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Example template for deploying a AWS Lambda with relevant chaos configuration.

Globals:
  Function:
    Timeout: 10

Resources:
  
  ChaosFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: DotnetChaosLambda.FunctionTest
      Handler: DotnetChaosLambda.FunctionTest::DotnetChaosLambda.FunctionTest.Function::LambdaHandler
      Runtime: dotnet6
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          CHAOS_PARAM: !Ref ChaosParameter
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref ChaosParameter
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /chaos
            Method: get
            
  ChaosParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: command
      Type: String
      Value: "{	\"FaultType\": \"exception\",	\"Delay\": 400,	\"IsEnabled\": true,	\"ErrorCode\": 404,	\"ExceptionMsg\": \"chaos\",	\"Rate\": 0.5,	\"CacheTTL\": 5 }"
      Description: SSM Parameter for chaos configuration

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/chaos/"
